
export enum ResiduoType  {
    TODOS = "TODOS OS TIPOS",
    PLASTICO = "PLASTICO",
    VIDRO = "VIDRO",
    METAL = "METAL",
    MADEIRA = "MADEIRA",
    ORGANICO = "ORGANICO",
    ELETRONICO = "ELETRONICO",
    PAPEL = "PAPEL",
    PERIGOSO = "PERIGOSO",
    ENTULHO = "ENTULHO",
    INDEFINIDO = "INDEFINIDO"
}