
export enum ResiduoType  {
    TODOS = "TODOS OS TIPOS",
    PLASTICO = "PLASTICO",
    VIDRO = "VIDRO",
    METAL = "METAL",
    ALVENARIA = "CONSTRUCAO",
    MADEIRA = "MADEIRA",
    ORGANICO = "ORGANICO",
    ELETRONICOS = "ELETRONICOS",
    PAPEL = "PAPEL",
    PERIGOSOS = "PERIGOSOS",
    VOLUMOSOS = "VOLUMOSOS"
}